export type AssessmentStatus = "Active" | "Draft" | "Scheduled" | "Completed" | "Archived";
export type Difficulty = "Beginner" | "Intermediate" | "Advanced";
export type QuestionType = "MCQ" | "Coding" | "Scenario Based" | "True/False" | "Fill in the Blank";

export interface Assessment {
  id: string; title: string; description: string; category: string; skill: string; difficulty: Difficulty; questions: number; participants: number; completionRate: number; status: AssessmentStatus; duration: number; passingMarks: number; attemptsAllowed: number; createdBy: string; assignedDepartments: string[]; assignedStudents: number; averageScore: number; topPerformers: string[]; createdDate: string;
}
export interface Question { id: string; text: string; skill: string; type: QuestionType; difficulty: Difficulty; status: "Active" | "Disabled"; options: string[]; correctAnswer: string; explanation: string; marks: number; timeLimit: number; }
export interface Participation { assessment: string; participants: number; completed: number; ongoing: number; notStarted: number; averageScore: number; highestScore: number; lowestScore: number; department: string; }
export interface DepartmentPerformance { department: string; studentsAssigned: number; completion: number; averageScore: number; highestScore: number; pendingStudents: number; }
export interface UpcomingAssessment { name: string; department: string; scheduledDate: string; duration: number; assignedStudents: number; status: "Scheduled"; }

const names = ["Python Fundamentals", "Java Programming", "React Basics", "SQL Queries", "Communication Skills", "Leadership Essentials", "Cloud Computing", "Machine Learning Readiness", "Cybersecurity Basics", "Prompt Engineering", "Git & GitHub", "Docker Essentials", "Node.js Assessment", "Data Structures", "JavaScript Fundamentals", "TypeScript Patterns", "AWS Foundations", "UI/UX Thinking", "Data Analysis", "Power BI Essentials", "DevOps Readiness", "Teamwork & Collaboration", "C++ Core Concepts", "Android Development", "Flutter Foundations"];
const skillByIndex = ["Python", "Java", "React", "SQL", "Communication", "Leadership", "Cloud Computing", "Machine Learning", "Cybersecurity", "Prompt Engineering", "Git", "Docker", "Node.js", "Data Structures", "JavaScript", "TypeScript", "AWS", "UI/UX", "Data Analysis", "Power BI", "DevOps", "Teamwork", "C++", "Android", "Flutter"];
const categoryByIndex = ["Technical", "Technical", "Technical", "Technical", "Soft Skills", "Soft Skills", "Domain", "Technical", "Domain", "Emerging", "Technical", "Technical", "Technical", "Technical", "Technical", "Technical", "Domain", "Domain", "Domain", "Domain", "Technical", "Soft Skills", "Technical", "Technical", "Technical"];
const statuses: AssessmentStatus[] = ["Active", "Active", "Active", "Active", "Completed", "Active", "Scheduled", "Active", "Draft", "Scheduled", "Active", "Active", "Active", "Completed", "Active", "Draft", "Active", "Active", "Completed", "Active", "Scheduled", "Active", "Draft", "Active", "Archived"];
const difficulties: Difficulty[] = ["Beginner", "Intermediate", "Intermediate", "Advanced", "Beginner", "Intermediate", "Intermediate", "Advanced", "Intermediate", "Advanced", "Beginner", "Intermediate", "Intermediate", "Advanced", "Beginner", "Advanced", "Intermediate", "Beginner", "Intermediate", "Intermediate", "Advanced", "Beginner", "Intermediate", "Intermediate", "Beginner"];
export const assessments: Assessment[] = names.map((title, index) => ({ id: `assessment-${index + 1}`, title, description: `${title} evaluates practical readiness through applied questions, realistic scenarios, and skill-focused decision making.`, category: categoryByIndex[index], skill: skillByIndex[index], difficulty: difficulties[index], questions: 20 + (index % 4) * 5, participants: 180 + index * 73, completionRate: 52 + ((index * 7) % 47), status: statuses[index], duration: 30 + (index % 4) * 15, passingMarks: 60 + (index % 3) * 5, attemptsAllowed: index % 3 === 0 ? 2 : 1, createdBy: index % 2 ? "Academic Success Team" : "SkillConnect Admin", assignedDepartments: ["Computer Engineering", "IT"].slice(0, index % 3 === 0 ? 1 : 2), assignedStudents: 420 + index * 38, averageScore: 64 + ((index * 5) % 28), topPerformers: ["Aarav Sharma", "Ishita Patel", "Rohan Mehta"], createdDate: `Aug ${String(2 + (index % 24)).padStart(2, "0")}, 2026` }));

const questionPrompts = ["Which approach best improves maintainability in a production project?", "Choose the safest response when requirements change during delivery.", "What is the primary purpose of this technique in a real team?", "Complete the statement used in a standard implementation.", "Which result would you expect from this code or workflow?"];
export const questions: Question[] = Array.from({ length: 40 }, (_, index) => ({ id: `question-${index + 1}`, text: `${questionPrompts[index % questionPrompts.length]} Question ${index + 1} focuses on ${skillByIndex[index % skillByIndex.length]}.`, skill: skillByIndex[index % skillByIndex.length], type: (["MCQ", "Coding", "Scenario Based", "True/False", "Fill in the Blank"] as QuestionType[])[index % 5], difficulty: difficulties[index % difficulties.length], status: index % 13 === 0 ? "Disabled" : "Active", options: ["Document the decision", "Ask for evidence", "Ship without review", "None of the above"], correctAnswer: "Document the decision", explanation: "This answer reflects a repeatable, evidence-led approach used in professional teams.", marks: 2 + (index % 4), timeLimit: 2 + (index % 5) }));

export const participation: Participation[] = assessments.slice(0, 12).map((assessment, index) => ({ assessment: assessment.title, participants: assessment.participants, completed: Math.round(assessment.participants * assessment.completionRate / 100), ongoing: 20 + index * 4, notStarted: 40 + index * 3, averageScore: assessment.averageScore, highestScore: Math.min(99, assessment.averageScore + 22), lowestScore: Math.max(30, assessment.averageScore - 24), department: ["AI & DS", "Computer Engineering", "IT", "Electronics"][index % 4] }));
export const departmentPerformance: DepartmentPerformance[] = ["AI & DS", "Computer Engineering", "IT", "Electronics", "Mechanical", "Civil"].map((department, index) => ({ department, studentsAssigned: 640 - index * 42, completion: 88 - index * 6, averageScore: 82 - index * 4, highestScore: 98 - index, pendingStudents: 44 + index * 19 }));
export const upcomingAssessments: UpcomingAssessment[] = ["Cloud Computing", "Prompt Engineering", "Leadership Essentials", "Machine Learning Readiness", "Docker Essentials"].map((name, index) => ({ name, department: ["IT", "AI & DS", "Mechanical", "Computer Engineering", "Electronics"][index], scheduledDate: `Sep ${String(12 + index * 4).padStart(2, "0")}, 2026`, duration: 45 + index * 15, assignedStudents: 180 + index * 55, status: "Scheduled" }));
export const lowCompletionAlerts = assessments.filter((assessment) => assessment.completionRate < 60).slice(0, 4).map((assessment) => ({ name: assessment.title, completion: assessment.completionRate, department: assessment.assignedDepartments[0], pendingStudents: assessment.assignedStudents - Math.round(assessment.assignedStudents * assessment.completionRate / 100) }));
export const categories = ["Technical", "Soft Skills", "Domain", "Emerging", "Behavioral"].map((name, index) => ({ name, assessments: [21, 8, 7, 4, 2][index], questions: [720, 168, 190, 104, 66][index], completion: [82, 88, 76, 64, 91][index], averageScore: [79, 84, 73, 68, 86][index] }));
export const assessmentKpis = [{ title: "Total Assessments", value: "42", trend: "+6 this quarter", icon: "library", accent: "bg-indigo-600" }, { title: "Active Assessments", value: "24", trend: "57% of library", icon: "activity", accent: "bg-emerald-600" }, { title: "Draft Assessments", value: "8", trend: "3 ready for review", icon: "file", accent: "bg-amber-500" }, { title: "Questions in Database", value: "1,248", trend: "+84 this month", icon: "database", accent: "bg-sky-500" }, { title: "Participation Rate", value: "84%", trend: "+5.4% quarter over quarter", icon: "users", accent: "bg-violet-600" }, { title: "Average Assessment Score", value: "78%", trend: "+2.8% from last cycle", icon: "award", accent: "bg-orange-500" }];
