export type ReportFormat = "PDF" | "CSV" | "Excel";
export type ReportStatus = "Ready" | "Generating" | "Scheduled";
export interface Report { id: string; name: string; category: string; generatedBy: string; date: string; format: ReportFormat; status: ReportStatus; description: string; }
export interface DepartmentReport { department: string; students: number; readiness: number; placement: number; completion: number; skillGaps: number; topSkill: string; weakestSkill: string; }
export const reportCategories = [
  { name: "Student Readiness Report", description: "Readiness distribution across student cohorts and departments.", icon: "users", lastGenerated: "Aug 28, 2026" }, { name: "Skill Gap Report", description: "Priority gaps connecting student proficiency to market demand.", icon: "target", lastGenerated: "Aug 27, 2026" }, { name: "Placement Report", description: "Placement outcomes, offers, and conversion by cycle.", icon: "briefcase", lastGenerated: "Aug 26, 2026" }, { name: "Industry Demand Report", description: "Skills and capabilities requested by hiring partners.", icon: "trending", lastGenerated: "Aug 25, 2026" }, { name: "Assessment Performance Report", description: "Completion, performance, and assessment participation signals.", icon: "clipboard", lastGenerated: "Aug 24, 2026" }, { name: "Department Performance Report", description: "Department-level readiness and placement benchmarks.", icon: "building", lastGenerated: "Aug 22, 2026" }, { name: "Certification Report", description: "Certification progress and verified learner achievements.", icon: "award", lastGenerated: "Aug 20, 2026" }, { name: "Internship Conversion Report", description: "Internship-to-offer movement across industry partners.", icon: "arrow", lastGenerated: "Aug 18, 2026" },
];
const reportNames = ["Quarterly Student Readiness", "Industry Demand Snapshot", "Placement Outcomes FY26", "AI & DS Department Review", "Assessment Completion Audit", "Cloud Skills Gap Analysis", "Internship Conversion Summary", "Certification Progress", "Engineering Cohort Health", "Top Skills by Department", "Graduate Placement Pack", "Hiring Partner Brief", "Soft Skills Readiness", "Emerging Skills Watchlist", "Application Funnel Review", "Academic Year Summary", "Employer Skills Matrix", "Technical Assessment Review", "Placement Readiness Forecast", "Institutional Outcomes Pack"];
export const reports: Report[] = reportNames.map((name, index) => ({ id: `report-${index + 1}`, name, category: reportCategories[index % reportCategories.length].name, generatedBy: index % 3 === 0 ? "SkillConnect Admin" : index % 3 === 1 ? "Placement Cell" : "Academic Success Team", date: `Aug ${String(3 + (index % 25)).padStart(2, "0")}, 2026`, format: (["PDF", "CSV", "Excel"] as ReportFormat[])[index % 3], status: (index % 7 === 0 ? "Generating" : index % 5 === 0 ? "Scheduled" : "Ready") as ReportStatus, description: "Institutional analytics prepared from the current SkillConnect reporting cycle." }));
export const reportKpis = [{ title: "Reports Generated", value: "148", trend: "+18 this month", icon: "file", accent: "bg-indigo-600" }, { title: "Department Reports", value: "18", trend: "All departments covered", icon: "building", accent: "bg-sky-500" }, { title: "Placement Reports", value: "36", trend: "+6 this quarter", icon: "briefcase", accent: "bg-emerald-600" }, { title: "Skill Gap Reports", value: "52", trend: "12 need review", icon: "target", accent: "bg-orange-500" }];
export const departmentReports: DepartmentReport[] = [{ department: "AI & DS", students: 1840, readiness: 84, placement: 88, completion: 91, skillGaps: 168, topSkill: "Python", weakestSkill: "Cloud Computing" }, { department: "Computer Engineering", students: 2480, readiness: 81, placement: 82, completion: 88, skillGaps: 246, topSkill: "Java", weakestSkill: "Communication" }, { department: "IT", students: 2260, readiness: 78, placement: 76, completion: 84, skillGaps: 218, topSkill: "JavaScript", weakestSkill: "AWS" }, { department: "Electronics", students: 1720, readiness: 73, placement: 69, completion: 79, skillGaps: 204, topSkill: "C++", weakestSkill: "Data Analysis" }, { department: "Mechanical", students: 1480, readiness: 68, placement: 61, completion: 75, skillGaps: 266, topSkill: "Teamwork", weakestSkill: "Communication" }, { department: "Civil", students: 980, readiness: 64, placement: 54, completion: 71, skillGaps: 146, topSkill: "AutoCAD", weakestSkill: "Digital Tools" }];
export const reportInsights = [{ title: "Cloud Computing demand increased 28%", detail: "Cloud roles now represent the largest readiness gap in the current hiring cycle.", tag: "Market signal" }, { title: "Prompt Engineering adoption increased", detail: "More than 420 students have added the skill to their learning profile.", tag: "Emerging" }, { title: "Mechanical needs soft skill intervention", detail: "Communication is the weakest skill across the Mechanical cohort.", tag: "Action suggested" }, { title: "Highest placement growth in AI & DS", detail: "AI & DS improved placement outcomes by 12 points this cycle.", tag: "Positive signal" }];
