"use client";
import { MoreHorizontal } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import type { Application } from "@/lib/mock-data/applications";
import { ApprovalStatusBadge } from "@/components/admin/opportunities/approval-status-badge";
import { ApplicationProgress } from "@/components/admin/opportunities/application-progress";

export function ApplicationTable({ applications, onView, onAction }: { applications: Application[]; onView: (item: Application) => void; onAction: (item: Application, action: string) => void }) {
  return <Table><TableHeader className="sticky top-0 z-10 bg-white"><TableRow><TableHead>Student</TableHead><TableHead>Opportunity</TableHead><TableHead>Company</TableHead><TableHead>Readiness</TableHead><TableHead>Applied date</TableHead><TableHead>Current stage</TableHead><TableHead>Status</TableHead><TableHead>Actions</TableHead></TableRow></TableHeader><TableBody>{applications.map((item) => <TableRow key={item.id}><TableCell><button onClick={() => onView(item)} className="text-left font-semibold text-indigo-700 hover:underline">{item.studentName}</button><p className="mt-1 text-xs text-muted">{item.department}</p></TableCell><TableCell className="max-w-44 text-xs">{item.opportunity}</TableCell><TableCell>{item.company}</TableCell><TableCell><ApplicationProgress stage={item.stage} /></TableCell><TableCell className="whitespace-nowrap text-xs text-muted">{item.appliedDate}</TableCell><TableCell><span className="whitespace-nowrap text-xs font-medium">{item.stage}</span></TableCell><TableCell><ApprovalStatusBadge status={item.stage} /></TableCell><TableCell><details className="relative"><summary className="inline-flex list-none"><Button variant="ghost" size="icon" aria-label={`Actions for ${item.studentName}`}><MoreHorizontal className="h-4 w-4" /></Button></summary><div className="absolute right-0 z-20 mt-1 w-40 rounded-xl border border-line bg-white p-1 shadow-lg">{["View Details", "Shortlist", "Schedule Interview", "Reject", "Mark Selected", "Mark Placed"].map((action) => <button key={action} className="block w-full rounded-lg px-3 py-2 text-left text-xs text-ink hover:bg-slate-50" onClick={() => onAction(item, action)}>{action}</button>)}</div></details></TableCell></TableRow>)}</TableBody></Table>;
}