"use client";
import type { Application } from "@/lib/mock-data/applications";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { ApprovalStatusBadge } from "@/components/admin/opportunities/approval-status-badge";

export function ApplicationDialog({ application, open, onOpenChange, onAction }: { application?: Application; open: boolean; onOpenChange: (open: boolean) => void; onAction: (action: string) => void }) {
  if (!application) return null;
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><div className="flex items-start gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-indigo-50 font-bold text-indigo-700">{application.studentInitials}</div><div><DialogTitle>{application.studentName}</DialogTitle><DialogDescription>{application.department} · {application.company}</DialogDescription></div></div></DialogHeader><div className="space-y-5 text-sm"><Info title="Student profile"><p>{application.department} student with a {application.recommendationScore}% placement recommendation score.</p><p className="mt-1 text-muted">Resume: {application.resumeStatus}</p></Info><div className="grid gap-5 sm:grid-cols-2"><Info title="Applied opportunity"><p>{application.opportunity}</p><p className="mt-1 text-muted">{application.company} · {application.appliedDate}</p></Info><Info title="Skill readiness"><p className="text-2xl font-semibold text-indigo-700">{application.readinessScore}%</p></Info></div><Info title="Application timeline"><ul className="space-y-1 text-muted">{application.timeline.map((item) => <li key={item}>{item}</li>)}</ul></Info><Info title="Assessment scores"><div className="grid gap-2 sm:grid-cols-3">{application.assessmentScores.map((item) => <div key={item.name} className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-muted">{item.name}</p><p className="mt-1 font-semibold">{item.score}%</p></div>)}</div></Info><Info title="Top skills"><p>{application.topSkills.join(" · ")}</p></Info><Info title="Skill gaps"><p className="text-muted">{application.skillGaps.join(" · ")}</p></Info><Info title="Interview feedback"><p className="leading-6 text-muted">{application.interviewFeedback}</p></Info></div><DialogFooter><Button variant="outline" onClick={() => onAction("Reject")}>Reject</Button><Button variant="outline" onClick={() => onAction("Schedule Interview")}>Schedule Interview</Button><Button onClick={() => onAction("Shortlist")}>Shortlist</Button><Button onClick={() => onAction("Mark Selected")}>Mark Selected</Button><Button onClick={() => onAction("Mark Placed")}>Mark Placed</Button></DialogFooter><div className="flex items-center gap-2 border-t border-line pt-3 text-xs">Current stage <ApprovalStatusBadge status={application.stage} /></div></DialogContent></Dialog>;
}
function Info({ title, children }: { title: string; children: React.ReactNode }) { return <div><p className="text-xs font-semibold uppercase tracking-[0.12em] text-muted">{title}</p><div className="mt-2 text-ink">{children}</div></div>; }