"use client";
import { useState } from "react";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import type { Opportunity, OpportunityType } from "@/lib/mock-data/opportunities";
import { ApprovalStatusBadge } from "@/components/admin/opportunities/approval-status-badge";

export function OpportunityDialog({ opportunity, open, onOpenChange, onAction, mode = "details", onSave }: { opportunity?: Opportunity; open: boolean; onOpenChange: (open: boolean) => void; onAction: (action: string) => void; mode?: "details" | "form"; onSave?: (opportunity: Opportunity) => void }) {
  if (mode === "form") return <OpportunityForm opportunity={opportunity} open={open} onOpenChange={onOpenChange} onSave={onSave} />;
  if (!opportunity) return null;
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><div className="flex items-start justify-between gap-4"><div><DialogTitle>{opportunity.title}</DialogTitle><DialogDescription>{opportunity.company.name} · {opportunity.department}</DialogDescription></div><ApprovalStatusBadge status={opportunity.status} /></div></DialogHeader><div className="space-y-5 text-sm"><InfoSection title="Company information"><p>{opportunity.company.name} · {opportunity.company.industry}</p><p className="mt-1 text-muted">{opportunity.location}</p></InfoSection><InfoSection title="Job description"><p className="leading-6 text-muted">{opportunity.description}</p></InfoSection><div className="grid gap-5 sm:grid-cols-2"><InfoSection title="Required skills"><p className="text-muted">{opportunity.skills.join(" · ")}</p></InfoSection><InfoSection title="Eligibility criteria"><ul className="space-y-1 text-muted">{opportunity.eligibility.map((item) => <li key={item}>• {item}</li>)}</ul></InfoSection><InfoSection title="Salary / stipend"><p>{opportunity.salary}</p></InfoSection><InfoSection title="Deadline & openings"><p>{opportunity.deadline} · {opportunity.openings} openings</p></InfoSection></div><InfoSection title="Application statistics"><p className="text-muted">{opportunity.applications.toLocaleString()} applications received · {Math.round(opportunity.applications / Math.max(1, opportunity.openings))} applicants per opening</p></InfoSection><InfoSection title="Top matching student skills"><p className="text-muted">{opportunity.topSkills.join(" · ")}</p></InfoSection><InfoSection title="Approval history"><ul className="space-y-1 text-muted">{opportunity.approvalHistory.map((item) => <li key={item}>{item}</li>)}</ul></InfoSection></div><DialogFooter><Button variant="outline" onClick={() => onAction("Edit")}>Edit Opportunity</Button><Button variant="outline" onClick={() => onAction("Reject")}>Reject Opportunity</Button><Button onClick={() => onAction("Approve")}>Approve Opportunity</Button></DialogFooter><Input className="hidden" aria-hidden="true" /></DialogContent></Dialog>;
}

function OpportunityForm({ opportunity, open, onOpenChange, onSave }: { opportunity?: Opportunity; open: boolean; onOpenChange: (open: boolean) => void; onSave?: (opportunity: Opportunity) => void }) {
  const [title, setTitle] = useState(opportunity?.title ?? "");
  const [company, setCompany] = useState(opportunity?.company.name ?? "TCS");
  const [type, setType] = useState<OpportunityType>(opportunity?.type ?? "Internship");
  const [department, setDepartment] = useState(opportunity?.department ?? "Engineering");
  const submit = (event: React.FormEvent) => { event.preventDefault(); onSave?.({ ...(opportunity ?? { id: `opportunity-${Date.now()}`, applications: 0, deadline: "Oct 31, 2026", status: "Draft" as const, description: "", eligibility: ["Final-year students or graduates"], location: "Bengaluru", salary: "₹30,000/mo", openings: 1, topSkills: ["Communication"], approvalHistory: ["Created locally · awaiting review"] }), title, type, department, company: { id: company.toLowerCase(), name: company, industry: "Technology Services", logo: company.slice(0, 3).toUpperCase() }, skills: opportunity?.skills ?? ["Communication", "Teamwork"] }); onOpenChange(false); };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>{opportunity ? "Edit opportunity" : "Add opportunity"}</DialogTitle><DialogDescription>Maintain opportunity details for a future approval review.</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-4"><label className="block space-y-1.5 text-sm font-medium">Job title<Input required value={title} onChange={(event) => setTitle(event.target.value)} placeholder="e.g. Product Analyst" /></label><div className="grid gap-4 sm:grid-cols-2"><label className="space-y-1.5 text-sm font-medium">Company<select className="h-10 w-full rounded-xl border border-line bg-white px-3 text-sm" value={company} onChange={(event) => setCompany(event.target.value)}>{["TCS", "Infosys", "Accenture", "Wipro", "Google", "Microsoft", "Amazon"].map((item) => <option key={item}>{item}</option>)}</select></label><label className="space-y-1.5 text-sm font-medium">Opportunity type<select className="h-10 w-full rounded-xl border border-line bg-white px-3 text-sm" value={type} onChange={(event) => setType(event.target.value as OpportunityType)}><option>Internship</option><option>Full-Time</option><option>Apprenticeship</option></select></label></div><label className="block space-y-1.5 text-sm font-medium">Department<Input required value={department} onChange={(event) => setDepartment(event.target.value)} /></label><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button type="submit">Save opportunity</Button></DialogFooter></form></DialogContent></Dialog>;
}
function InfoSection({ title, children }: { title: string; children: React.ReactNode }) { return <div><p className="text-xs font-semibold uppercase tracking-[0.12em] text-muted">{title}</p><div className="mt-2 text-ink">{children}</div></div>; }