"use client";
import { MoreHorizontal } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import type { Opportunity } from "@/lib/mock-data/opportunities";
import { ApprovalStatusBadge } from "@/components/admin/opportunities/approval-status-badge";

export function OpportunityTable({ opportunities, onView, onEdit, onAction }: { opportunities: Opportunity[]; onView: (item: Opportunity) => void; onEdit: (item: Opportunity) => void; onAction: (item: Opportunity, action: string) => void }) {
  return <Table><TableHeader className="sticky top-0 z-10 bg-white"><TableRow><TableHead>Job title</TableHead><TableHead>Company</TableHead><TableHead>Type</TableHead><TableHead>Required skills</TableHead><TableHead>Applications</TableHead><TableHead>Deadline</TableHead><TableHead>Status</TableHead><TableHead>Actions</TableHead></TableRow></TableHeader><TableBody>{opportunities.map((item) => <TableRow key={item.id}><TableCell><button onClick={() => onView(item)} className="max-w-48 text-left font-semibold text-indigo-700 hover:underline">{item.title}</button></TableCell><TableCell className="whitespace-nowrap">{item.company.name}</TableCell><TableCell><span className="whitespace-nowrap text-xs text-muted">{item.type}</span></TableCell><TableCell><div className="flex max-w-48 flex-wrap gap-1">{item.skills.slice(0, 2).map((skill) => <Badge key={skill} className="normal-case tracking-normal">{skill}</Badge>)}{item.skills.length > 2 && <Badge>+{item.skills.length - 2}</Badge>}</div></TableCell><TableCell>{item.applications.toLocaleString()}</TableCell><TableCell className="whitespace-nowrap text-xs text-muted">{item.deadline}</TableCell><TableCell><ApprovalStatusBadge status={item.status} /></TableCell><TableCell><details className="relative"><summary className="inline-flex list-none"><Button variant="ghost" size="icon" aria-label={`Actions for ${item.title}`}><MoreHorizontal className="h-4 w-4" /></Button></summary><div className="absolute right-0 z-20 mt-1 w-36 rounded-xl border border-line bg-white p-1 shadow-lg">{["View Details", "Approve", "Reject", "Edit", "Disable"].map((action) => <button key={action} className="block w-full rounded-lg px-3 py-2 text-left text-xs text-ink hover:bg-slate-50" onClick={() => action === "View Details" ? onView(item) : action === "Edit" ? onEdit(item) : onAction(item, action)}>{action}</button>)}</div></details></TableCell></TableRow>)}</TableBody></Table>;
}